controlImage: free5gmano/free5gc-control-plane:stage3.0.4
mongodbImage: free5gmano/nextepc-mongodb

generic:
  interface: br0
  networkImage: sdnvortex/network-controller:v0.4.9
mongodb:
  enabled: true
  port: 27017
amf:
  interface: eth1
  addresses: 192.168.2.162/23
  ip: 192.168.2.162
  enabled: true
  port: 29502
ausf:
  interface: eth1
  addresses: 192.168.2.164/23
  ip: 192.168.2.164
  enabled: true
nrf:
  interface: eth1
  addresses: 192.168.2.165/23
  ip: 192.168.2.165
  enabled: true
  port: 29510
nssf:
  interface: eth1
  addresses: 192.168.2.166/23
  ip: 192.168.2.166
  enabled: true 
pcf:
  interface: eth1
  addresses: 192.168.2.169/23
  ip: 192.168.2.169
  enabled: true
smf:
  interface: eth1
  addresses: 192.168.2.163/23
  ip: 192.168.2.163
  upfIP: 192.168.2.160
  enabled: true
udm:
  interface: eth1
  addresses: 192.168.2.167/23
  ip: 192.168.2.167
  enabled: true
udr:
  interface: eth1
  addresses: 192.168.2.168/23
  ip: 192.168.2.168
  enabled: true
webui:
  interface: eth1
  addresses: 192.168.2.162/23
  ip: 192.168.2.162
  enabled: true

webui:
  image: free5gmano/open5gs-webui:v2.1.7
  enabled: true
  ports:
    webuiService:
      name: webui
      protocol: TCP
      port: 5000
      nodePort: 31111