{{- if .Values.udm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udm-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}udm
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}udm
    spec:
      containers:
      - name: myapp-container
        image: {{ .Values.controlImage }} 
        command: ["/bin/sh"]
        args: ["-c", "sleep 7s && ./bin/udm"]
        volumeMounts:
        - name: udmcfg
          mountPath: /free5gc/config/udmcfg.yaml
          subPath: udmcfg.yaml
      volumes:
      - name: udmcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: udmcfg.yaml
            path: udmcfg.yaml
{{- end }}
