{{- if .Values.smf.enabled }}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smf-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-smf
    spec:
      containers:      
      - name: myapp-container
        image: {{ .Values.open5gcImage }}
        command: ["/bin/sh"]
        args: ["-c", "./bin/open5gs-smfd"]
        volumeMounts:
        - name: open5gs-smfcfg
          mountPath: /open5gs/install/etc/open5gs/smf.yaml
          subPath: smf.yaml
        - name: open5gs-freediameter-smfcfg
          mountPath: /open5gs/install/etc/freeDiameter/smf.conf
          subPath: smf.conf
      initContainers:
      - name: init-network-client
        image: {{ .Values.generic.networkImage }}
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b={{ .Values.generic.interface }}", "-n={{ .Values.smf.interface }}", "-i={{ .Values.smf.addresses }}", "-g={{ .Values.generic.gateway }}"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: open5gs-smfcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: smf.yaml
            path: smf.yaml
      - name: open5gs-freediameter-smfcfg
        configMap:
          name: {{ .Release.Name }}-freediameter-configmap
          items: 
          - key: smf.conf
            path: smf.conf
{{- end }}