{{- if .Values.webui.enabled }}
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: free5gc-webui
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:
      - name: free5gc-webui
        image: cewuandy/free5gc-webui
        ports:
        - containerPort: 3000
{{- end }}