{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webui-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}webui
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}webui
    spec:
      containers:
      - name: open5gs-webui
        command: ["/bin/bash", "-c"]
        args: ["npm run start"]
        image: free5gmano/open5gs-webui:v2.1.7
        env:
        - name: DB_URI
          value: "mongodb://{{ .Release.Name }}-mongodb-svc/open5gs"
{{- end }}