{{- if .Values.mme.enabled }}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mme-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mme
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mme
    spec:
      containers:      
      - name: myapp-container
        image: {{ .Values.open5gcImage }}
        command: ["/bin/sh"]
        args: ["-c", "./bin/open5gs-mmed"]
        volumeMounts:
        - name: open5gs-mmecfg
          mountPath: /open5gs/install/etc/open5gs/mme.yaml
          subPath: mme.yaml
        - name: open5gs-freediameter-mmecfg
          mountPath: /open5gs/install/etc/freeDiameter/mme.conf
          subPath: mme.conf
      initContainers:
      - name: init-network-client
        image: {{ .Values.generic.networkImage }}
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b={{ .Values.generic.interface }}", "-n={{ .Values.mme.interface }}", "-i={{ .Values.mme.addresses }}", "-g={{ .Values.generic.gateway }}"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: open5gs-mmecfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: mme.yaml
            path: mme.yaml
      - name: open5gs-freediameter-mmecfg
        configMap:
          name: {{ .Release.Name }}-freediameter-configmap
          items: 
          - key: mme.conf
            path: mme.conf
{{- end }}