{{- if .Values.smf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smf-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}smf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}smf
    spec:
      containers:
      - name: myapp-container
        image: {{ .Values.controlImage }} 
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/smf"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: smfcfg
          mountPath: free5gc/config/smfcfg.yaml
          subPath: smfcfg.yaml
        - name: uerouting
          mountPath: free5gc/config/uerouting.yaml
          subPath: uerouting.yaml
      volumes:
      - name: smfcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: smfcfg.yaml
            path: smfcfg.yaml
      - name: uerouting
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: uerouting.yaml
            path: uerouting.yaml
{{- end }}

