{{- if .Values.udm.enabled }}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-udm-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-udm
    spec:
      containers:      
      - name: myapp-container
        image: {{ .Values.open5gcImage }}
        command: ["/bin/sh"]
        args: ["-c", "./bin/open5gs-udmd"]
        volumeMounts:
        - name: open5gs-udmcfg
          mountPath: /open5gs/install/etc/open5gs/udm.yaml
          subPath: udm.yaml
      initContainers:
      - name: init-network-client
        image: {{ .Values.generic.networkImage }}
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b={{ .Values.generic.interface }}", "-n={{ .Values.udm.interface }}", "-i={{ .Values.udm.addresses }}", "-g={{ .Values.generic.gateway }}"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: open5gs-udmcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: udm.yaml
            path: udm.yaml
{{- end }}