{{- if .Values.pcf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pcf-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}pcf
    spec:
      containers:
      - name: myapp-container
        image: {{ .Values.controlImage }} 
        command: ["/bin/sh"]
        args: ["-c", "sleep 7s && ./bin/pcf"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: pcfcfg
          mountPath: /free5gc/config/pcfcfg.yaml
          subPath: pcfcfg.yaml
      volumes:
      - name: pcfcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: pcfcfg.yaml
            path: pcfcfg.yaml
{{- end }}
