{{- if .Values.udr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udr-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}udr
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}udr
    spec:
      containers:
      - name: myapp-container
        image: {{ .Values.controlImage }} 
        command: ["/bin/sh"]
        args: ["-c", "sleep 7s && ./bin/udr"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: udrcfg
          mountPath: /free5gc/config/udrcfg.yaml
          subPath: udrcfg.yaml
      volumes:
      - name: udrcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: udrcfg.yaml
            path: udrcfg.yaml
{{- end }}

