{{- if .Values.mongodb.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/{{ .Release.Name }}"
{{- end }}