kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-configmap
apiVersion: v1
data:
  upf.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/upf.log

    upf:
        pfcp:
          - addr: {{ .Values.upf.ip }}
        gtpu:
          - addr: {{ .Values.upf.ip }}
        pdn:
          - addr: 10.45.0.1/16
          - addr: cafe::1/64

    smf:

    parameter:

    max:

    pool:

    time:
