{{- if .Values.upf.enabled }}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-upf-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}upf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}upf
    spec:
      containers:      
      - name: free5gc-upf-container
        image: {{ .Values.free5gcImage }}
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "/root/free5gc/setup-uptun.sh && sh -c /root/free5gc/free5gc-upfd"]
        volumeMounts:
          - mountPath: /dev/net/tun
            name: tun-volume
          - name: free5gc-config
            mountPath: /root/free5gc/install/etc/free5gc/free5gc.conf
            subPath: free5gc.conf
      initContainers:
      - name: init-network-client
        image: {{ .Values.generic.networkImage }}
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock",  "-b={{ .Values.generic.interface }}", "-n={{ .Values.upf.interface }}", "-i={{ .Values.upf.addresses }}"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: free5gc-config
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: free5gc.conf
            path: free5gc.conf
{{- end }}