{{- if .Values.udm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udm-svc
spec:
  selector:
    app: {{ .Release.Name }}udm
  clusterIP: None # 10.96.100.7
  ports:
    - name: {{ .Values.udm.ports.sbi.name }}
      protocol: {{ .Values.udm.ports.sbi.protocol }}
      port: {{ .Values.udm.ports.sbi.port }}
{{- end }}