apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/{{ .Values.generic.interface }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "{{ .Values.generic.interface }}"
    }'