{{- if .Values.amf.enabled }}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-amf-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-amf
    spec:
      containers:      
      - name: myapp-container
        image: {{ .Values.open5gcImage }}
        command: ["/bin/sh"]
        args: ["-c", "./bin/open5gs-amfd"]
        volumeMounts:
        - name: open5gs-amfcfg
          mountPath: /open5gs/install/etc/open5gs/amf.yaml
          subPath: amf.yaml
      initContainers:
      - name: init-network-client
        image: {{ .Values.generic.networkImage }}
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b={{ .Values.generic.interface }}", "-n={{ .Values.amf.interface }}", "-i={{ .Values.amf.addresses }}", "-g={{ .Values.generic.gateway }}"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: open5gs-amfcfg
        configMap:
          name: {{ .Release.Name }}-configmap
          items: 
          - key: amf.yaml
            path: amf.yaml
{{- end }}